server {
    listen 80;
    server_name _;

    location /api/auth/ {
        rewrite ^/api/auth/(.*)$ /auth/$1 break;
        proxy_pass http://svc-auth:3001;
        proxy_set_header Host $host;
    }

    location /api/estoque/ {
        rewrite ^/api/estoque/(.*)$ /$1 break;
        proxy_pass http://svc-estoque:3002;
        proxy_set_header Host $host;
    }

    location /api/vendas/ {
        rewrite ^/api/vendas/(.*)$ /vendas/$1 break;
        proxy_pass http://svc-vendas:3003;
        proxy_set_header Host $host;
    }

    location /api/financeiro/ {
        rewrite ^/api/financeiro/(.*)$ /$1 break;
        proxy_pass http://svc-financeiro:3004;
        proxy_set_header Host $host;
    }

    location /api/fiscal/ {
        rewrite ^/api/fiscal/(.*)$ /$1 break;
        proxy_pass http://svc-fiscal:3005;
        proxy_set_header Host $host;
    }

    location /api/compras/ {
        rewrite ^/api/compras/(.*)$ /compras/$1 break;
        proxy_pass http://svc-compras:3006;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
